=== ssomani7/COEN_280_HW4/buildings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		   elementFormDefault="qualified">
		
	<xs:element name="buildingsTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="building" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
	<xs:element name="building">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="buildingCode"/>
				<xs:element ref="buildingName"/>
				<xs:element ref="position"/>
				<xs:element ref="address" minOccurs="0" maxOccurs="1"/>	
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
		   
	<xs:element name="buildingCode">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[A-Z][A-Z][A-Z]"/> 
			</xs:restriction>
		</xs:simpleType>
	</xs:element>		   
		   
	<xs:element name="buildingName" type="xs:string"/>
	
	<xs:element name="position">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="latitude">
					<xs:simpleType>
						<xs:restriction base="xs:decimal">
							<xs:fractionDigits value="6"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="longitude">
					<xs:simpleType>
						<xs:restriction base="xs:decimal">
							<xs:fractionDigits value="3"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	   
		
	<!-- You cannot use maxOccurs/minOccurs in the root element. You need context for that. -->
	<!-- Hence maxOccurs/minOccurs will give error if used alongside "address", as it root element -->	
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="streetNo" type="xs:nonNegativeInteger"/>
				<xs:element name="strName" type="xs:string"/>
				<xs:element name="city" type="xs:string"/>
				<xs:element name="state">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[A-Z][A-Z]"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="zip">
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:pattern value="[0-9][0-9][0-9][0-9][0-9]"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
		   
</xs:schema>

=== ssomani7/COEN_280_HW4/buildings.xml
<?xml version="1.0" encoding="UTF-8"?>

<buildingsTable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="buildings.xsd">
  
  <building>
    <buildingCode>KOH</buildingCode>
    <buildingName>King Olympic Hall</buildingName>
    <position>
      <latitude>34.024547</latitude>
      <longitude>-118.288</longitude>
    </position>
    <address>
      <streetNo>1027</streetNo>
      <strName>W 34th St</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90007</zip>
    </address>
  </building>
  
  <building>
    <buildingCode>CFX</buildingCode>
    <buildingName>Cromwell Field</buildingName>
    <position>
      <latitude>34.021631</latitude>
      <longitude>-118.289</longitude>
    </position>
    <address>
      <streetNo>1026</streetNo>
      <strName>W 34th St</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>
  
    <building>
    <buildingCode>JEP</buildingCode>
    <buildingName>JEP House</buildingName>
    <position>
      <latitude>34.022947</latitude>
      <longitude>-118.284</longitude>
    </position>
    <address>
      <streetNo>801</streetNo>
      <strName>W 34th St</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>
  
    <building>
    <buildingCode>SHC</buildingCode>
    <buildingName>Student Health Center</buildingName>
    <position>
      <latitude>34.023303</latitude>
      <longitude>-118.285</longitude>
    </position>
    <address>
      <streetNo>849</streetNo>
      <strName>W 34th St</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>
  
    <building>
    <buildingCode>LVY</buildingCode>
    <buildingName>Leavey Library</buildingName>
    <position>
      <latitude>34.021595</latitude>
      <longitude>-118.282</longitude>
    </position>
    <address>
      <streetNo>651</streetNo>
      <strName>W 34th St</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>
  
    <building>
    <buildingCode>VKC</buildingCode>
    <buildingName>Von KleinSmid Center</buildingName>
    <position>
      <latitude>34.021649</latitude>
      <longitude>-118.284</longitude>
    </position>
    <address>
      <streetNo>3518</streetNo>
      <strName>Trousdale</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>
  
    <building>
    <buildingCode>WPH</buildingCode>
    <buildingName>Waite Phillips Hall</buildingName>
    <position>
      <latitude>34.022289</latitude>
      <longitude>-118.284</longitude>
    </position>
    <address>
      <streetNo>3550</streetNo>
      <strName>Trousdale</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>
  
    <building>
    <buildingCode>JHH</buildingCode>
    <buildingName>John Hubbard Hall</buildingName>
    <position>
      <latitude>34.020101</latitude>
      <longitude>-118.284</longitude>
    </position>
    <address>
      <streetNo>615</streetNo>
      <strName>Childs Way</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>
  
    <building>
    <buildingCode>REG</buildingCode>
    <buildingName>Registration Building</buildingName>
    <position>
      <latitude>34.019603</latitude>
      <longitude>-118.282</longitude>
    </position>
    <address>
      <streetNo>611</streetNo>
      <strName>Childs Way</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>
  
    <building>
    <buildingCode>STU</buildingCode>
    <buildingName>Student Union</buildingName>
    <position>
      <latitude>34.020226</latitude>
      <longitude>-118.286</longitude>
    </position>
    <address>
      <streetNo>3551</streetNo>
      <strName>Trousdale</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>
  
    <building>
    <buildingCode>BKS</buildingCode>
    <buildingName>Bookstore</buildingName>
    <position>
      <latitude>34.020635</latitude>
      <longitude>-118.286</longitude>
    </position>
    <address>
      <streetNo>840</streetNo>
      <strName>Childs Way</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>
  
    <building>
    <buildingCode>RTH</buildingCode>
    <buildingName>Ronald Tutor Hall</buildingName>
    <position>
      <latitude>34.020137</latitude>
      <longitude>-118.29</longitude>
    </position>
    <address>
      <streetNo>3710</streetNo>
      <strName>McClinntock</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>
  
    <building>
    <buildingCode>SAL</buildingCode>
    <buildingName>Salvatori Com. Center</buildingName>
    <position>
      <latitude>34.01955</latitude>
      <longitude>-118.289</longitude>
    </position>
    <address>
      <streetNo>941</streetNo>
      <strName>W 37th Place</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>
  
    <building>
    <buildingCode>EEB</buildingCode>
    <buildingName>Electrical Engr Center</buildingName>
    <position>
      <latitude>34.019728</latitude>
      <longitude>-118.29</longitude>
    </position>
    <address>
      <streetNo>3715</streetNo>
      <strName>McClintock</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>
  
    <building>
    <buildingCode>OHE</buildingCode>
    <buildingName>Olin Hall Engineering</buildingName>
    <position>
      <latitude>34.020493</latitude>
      <longitude>-118.29</longitude>
    </position>
    <address>
      <streetNo>3650</streetNo>
      <strName>McClintock</strName>
      <city>Los Angeles</city>
      <state>CA</state>
      <zip>90089</zip>
    </address>
  </building>  
</buildingsTable>
